// packages/ui/src/routes/app/+page.svelte
<script lang="typescript">
	import * as mirrors from '$lib/index';
	import * as mirrorsTransporter from '@mirrors/transporter';

	new mirrors.App({
		target: document.body,
		props: {
			bufferMs: 100,
			createTransporter({ uid }) {
				return new mirrorsTransporter.SocketIoTransporter({
					uid,
					role: 'app',
					url: 'http://localhost:3100',
				});
			}
		}
	});
</script>

// packages/react/demo/app.tsx
import React from 'react';
import { createRoot } from 'react-dom/client';
import { App } from '../src/App';
import { SocketIoTransporter } from '@mirrors/transporter';

const RELAY_URL = 'http://localhost:3100';

function createTransporter({ uid, role }: { uid: string; role: string }) {
  return new SocketIoTransporter({ uid, role, url: RELAY_URL });
}

function AppPage() {
  return <App createTransporter={createTransporter} bufferMs={100} />;
}

const root = createRoot(document.getElementById('root')!);
root.render(<AppPage />);
